### ISSUE TITLE
adding wtforms

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#10]
All forms should be using WTForms.

Shouldn't be too hard to add this in now, as only login form needs to be converted to use WTForms.

I have experience with WTForms 1.0 but not anything beyond that, though I can't imagine it has changed all that much so it's probably going to be fine.

**Comment by robvdl** [comment]
Before you start creating forms.py I think we need to think ahead where we might have many forms, so having a single forms.py is not going to scale very well.

If you created a module called forms with an __init__.py and a forms/auth.py then you can put all auth forms (login form) in there.

**Comment by johndanielcurley** [comment]
I have updated the forms to use wtforms. However I am not sure if the view is correct. The form itself is minimal at the moment with little markup around it. Please review.

**Comment by robvdl** [comment]
The view code looks fine to me, will merge soon.

**Comment by robvdl** [comment]
The presentation (template) doesn't need to be that good at this point anyway as we have no design or theme yet, so anything will do for now.
