### ISSUE TITLE
dbshell command

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#12]
This would be nice to complete things, It's not super important, but would definitely be nice to have.

Basically we need to use the subprocess module to either open a sqlite, postgres, or mysql shell (those 3 will do for now), depending on what the DB connection string starts with.

You do have access to self.settings (which is the contents of the pyramidcms.ini file) in all management commands automatically, so you can then use something like this:

    if self.settings['sqlalchemy.url'].startswith('sqlite://')  ... etc

On MySQL and Postgresql you should grab the DB username and database name from the connection string (you may need a regex to split these out), but always ask the user for the DB password (Django does this too), otherwise running "pcms shell" on a server will get you straight in.

For SQLite you will probably have to grab the database filename from the connection string, so you can   use it as an argument when opening the SQLite shell.

**Comment by robvdl** [comment]
I would suggest you use just one regex to split the connection string up in one go, with capturing groups to grab all the bits you need out.

**Comment by johndanielcurley** [comment]
I have updated the initial draft on the branch feature-dbshell-command-12. Please review and advise of any changes if necessary. I am not sure of the absolute location of the sqlite3 database. Please advise if this is correct or requires changing.

**Comment by johndanielcurley** [comment]
I will also comment this file when completed.
