### ISSUE TITLE
Pressing ctrl+c on "pcms dbshell" command during password input

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#17]
It's really hard to get out of the password prompt for pcms dbshell using ctrl+c to cancel, not too sure what can be done about this though.

This is not really that important though.

**Comment by robvdl** [comment]
I am not sure what can even be done here, if we can capture ctrl+c somehow and clean up but I am not sure.

**Comment by johndanielcurley** [comment]
I'll do some research and see what I can come up with.

**Comment by robvdl** [comment]
You can if you want, but like I said this isn't really important, the other tickets are more important.

**Comment by johndanielcurley** [comment]
I've wrapped the command in a try: except: block so hopefully it will solve the issue.

**Comment by johndanielcurley** [comment]
Should be fixed now.

**Comment by robvdl** [comment]
awesome! it's fixed indeed now.
