### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#18]
We need to create a simple REST API at some point.

Not sure if we want to do this in plain Pyramid views (using view classes), or using Mozilla Cornice.

I would start with implementing the GET's first as they are the easiest, so for example "return a list of users", and "return one user".

Please use the model.serialize() method for this, which has already been implemented, I think in most cases for an API we need to call this with full=True, though not always as in some cases this could generate very large requests.

**Comment by robvdl** [comment]
Oh yeah, JSON only please, don't even bother with other formats i.e. XML or YAML.

**Comment by robvdl** [comment]
PUT and POST will be the hardest as they also require deserialization code which we don't have yet, so I would leave those till last, though DELETE should be easy too.

**Comment by johndanielcurley** [comment]
Okay, will start this.

**Comment by robvdl** [comment]
I'm still a bit undecided whether we'll need cornice or not.  I don't remember much about it, if it's going to give us much of benefit, or if using regular pyramid view class would be enough.

**Comment by robvdl** [comment]
I've been looking at the API base class code again, as I haven't look at it for a while, so picking it up again.

So the thing is, originally it was modelled after TastyPie, I only barely made a start on the collection_get method, it uses a Paginator object that I implemented which is much like Django's Paginator class.  The thing is, looking at it now, the page number is still hard-coded to page 1 in the collection_get methodl, so this code was obviously not finished yet.

Also, TastyPie doesn't use pages (e.g. ?page=1 parameter in the URL), instead it uses offset (e.g. ?offset=10 in the url), which means you can navigate 1 row at a time, rather than 1 page at a time.  Using an offset is more flexible than a page at a time and would be preferred.

However, the current Paginator/Page objects I implemented only handles pages and not offsets.

I would either need to update these so you can move in offset rather than in pages at a time, or make the API use pages instead.

I found that TastyPie has it's own Paginator object that uses limit/offset rather than page, which is something that we might want.

http://django-tastypie.readthedocs.org/en/latest/paginator.html

I'm going to look into this a bit more in detail and make a decision to what we will do here, either do what TastyPie does and use ?offset=, or just use ?page= and keep the existing Paginator class as-is.

**Comment by johndanielcurley** [comment]
I think some of the tests we ported over are not consistent as well with
the syntax. We should do a code audit of everything we've imported so the
code is the same.

On Wed, Mar 4, 2015 at 10:04 PM, Rob van der Linde <notifications@github.com

**Comment by robvdl** [comment]
I don't think that is the case though, these test are just different in that they test an API base class, it has to be subclassed (which is what the test does) to generate some fake API's

About the only thing that is different, is the lack of description/docstring in the tests to say what each test is trying to do.

**Comment by robvdl** [comment]
Django rest framework seems to paginate one page at a time, rather than using offset like TastyPie.

Maybe we should continue to use pages rather than offset? Though TastyPie uses offset, on the front end I would translate that back in to a page in my gridview anyway and paginate one page at a time.  Never have I actually needed to paginate based on offset.  Using the ?page=1 ?page=2 would definitely be simpler and we don't have to copy exactly what TastyPie does to the letter!

**Comment by robvdl** [comment]
So rather than using ?offset= and ?limit= in the URL, maybe we should break the TastyPie compatibility here, and use ?page= and ?page_size= instead.

**Comment by robvdl** [comment]
Django Rest Framework is similar but it uses "paginate_by" instead of "page_size", it also uses "results" for the data it returns, while we uses "objects" and "meta" like TastyPie does.

http://www.django-rest-framework.org/api-guide/pagination/

I think I prefer page_size though.

**Comment by johndanielcurley** [comment]
Page size seems to work. Also I need some help with my unit test mocking so
I might push my code and you can have a look.

**Comment by robvdl** [comment]
This should be broken up into smaller tasks instead of one mega task.
