### ISSUE TITLE
createsuperuser command

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#19]
Mostly like Django, a management command that:

* Asks the user for a username, email and password (verify by asking password twice)
* Create the user in the database and exit

To create the user, use:

    user = User(username="foo", superuser=True)
    user.set_password("password")
    user.save()

Don't just use password as a kwarg when creating the User object or it won't encrypt the password and will just save whatever you give it, that is why you call set_password() after creating the User but before calling save.

Also, this project is for Python 3 only, so only use Python 3 methods should be used for acquiring user input, no Python 2 code for backwards compatibility please.

**Comment by johndanielcurley** [comment]
I was wondering what we could do about colour console output? If pyramid already has this in it's logging class or if we could write a class that we could import like django does for highlighting?

**Comment by robvdl** [comment]
Not really related to this particular ticket, but we don't current do request logging of any type yet.

You might get it automatically when you change the logging levels for the gunicorn or pyramid loggers (maybe), or we have to manually do request logging, but anyway.. that doesn't belong under this ticket.

**Comment by johndanielcurley** [comment]
Please check latest commit for this branch.
