### ISSUE TITLE
bug: cli.get_command_list strips trailing y and p characters.

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#28]
there is a statement f.strip('.py') that is doing this, needs to get fixed, but in the scaffold branch

**Comment by robvdl** [comment]
note to self: the fix is to use f[:-3]

**Comment by johndanielcurley** [comment]
Okay, so you're going to fix this along with the other fix that you've already pushed on the scaffold branch? So I just carry on with working on the shell command and integrating it into pcms? Also do we want to automatically load the models into the shell?

**Comment by robvdl** [comment]
I was thinking there is so much flux right now it might be the best to wait until that branch gets merged first, hopefully nearing the end of this weekend.
