### ISSUE TITLE
collectstatic: ignore common private glob-style patterns 'CVS', '.*' and '*~' by default (unless using --no-default-ignore)

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#39]
this is what Django's collectstatic command does, folders like .git and files and folders like .gitignore should not be copied by default.

**Comment by robvdl** [comment]
You might want to take the other collectstatic task on first, I had a stab at this one already about a week or so ago, and though it was easy enough to modify the existing code to ignore **files** starting with a dot (like .gitignore), it was a bit trickier to ignore whole **folders** (and their subfolders) that start with a dot, at least with the existing algorithm where os.walk() was used it was a bit tricky.  This is why I put this task aside for later at the time.

Feel free to have a stab at it though, just bear in mind that when you get a folder starting with a dot, you have to ignore all it's contents and subfolders too.

**Comment by johndanielcurley** [comment]
Thanks. Will keep that in mind.
