### ISSUE TITLE
Front-end assets pipe

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#4]
Setup:

* package.json for node.js that installs Grunt, etc.
* Gruntfile.js
* Bower
* Install and run sass from Gruntfile (lets look at using libsass instead of Ruby Sass)
* minification, concatenation of .js files
* ...

**Comment by johndanielcurley** [comment]
Can we develop some type of theming system which say autocompiles or is drag/drop?

**Comment by robvdl** [comment]
It has a "watch" rule in the Gruntfile which does very fast rebuilds while in dev mode... when it notices you save a file, so yeah it autocompiles.

the "build" rule only runs the build once and generates an optimised build.

**Comment by robvdl** [comment]
At this point we are focussing on backend code only and are putting the frontend on hold for a while.

Some choices of possible frontend frameworks were React + Browserify, or EmberJS but I want to look a bit more into EmberJS first.

**Comment by robvdl** [comment]
Closing this for now, because the front end has not yet been decided on and pushed back a bit, so we can concentrate on the backend.
