### ISSUE TITLE
collectstatic: option to clear existing files first (--clear or -c)

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#40]
just like Django's command

**Comment by robvdl** [comment]
this one should be quite straight forward:

* add an option flag to the collectstatic command (--clear and -c should both work)
* this flag, when set should clear the contents of the collection dir including subfolders (but not delete the collection dir itself)

**Comment by johndanielcurley** [comment]
Should I write a test for this functionality?
