### ISSUE TITLE
API index page

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#43]
We need an API "home" or "index" page, which will be a service that lists all the resources and services published by the API, it should return something like this:

```
{
    "resources": [
        "/api/user",
        "/api/group",
        "/api/permission"
    ],
    "services": [
        "/api/login",
        "/api/logout"
    ]
}
```

This may end up taking a while, so it's OK to spread this over a few commits and take your time.

First, cornice has a function you can call to get a list of all the available services, but it hasn't got a way to return all the available resources.  We do know however, that for every resource, Cornice will create two services behind the scenes, for example if the resource was /api/user then it creates two services for that resource: /api/user and /api/user/{id}, these two services can be "grouped" into a resource basically.

First, we need some sort of function that gets a list of all the services published from Cornice, and it should then identify which of those services can be grouped into a resource, and which services are not part of a resource.  The function should return a list of resources and a list of services.

The second stage, is to create a service located at the URL /api that will publish the list of resources and services, using the sample output above.

The service should be located in pyramidcms/api/services (the folder may need to be created)

**Comment by robvdl** [comment]
This should be a service that only implements GET, other request methods make no sense for this service.  For now, only JSON output is fine.

**Comment by johndanielcurley** [comment]
Thanks Rob. I will get going on this.

**Comment by robvdl** [comment]
Sorry to say I kind of already have implemented this in the end, because I needed it elsewhere and it was taking a while.  will merge it tonight if I can.

**Comment by johndanielcurley** [comment]
Fair enough, I have been quite busy with things lately and only just sat
down to have a look at it the other day. I think I might take a break from
the project to focus on other things. You seem to have it mapped out though
and a good general direction of where you're going.
