### ISSUE TITLE
loaddata and dumpdata commands

### ISSUE THREAD

**Issue by robvdl** [robvdl/pyramidcms#8]
At the moment there is a loaddata command that inserts some test data directly, this is just temporary because the loaddata command should load a JSON fixture instead and dumpdata should create these JSON fixtures.

It would be nice to keep the format of the JSON file similar to Django fixtures for the sake of familiarity.

Unlike Django however, we do NOT want to support other formats for fixtures as well like Yaml and XML.

**Comment by johndanielcurley** [comment]
I can work on this if you'd like.

**Comment by robvdl** [comment]
I've already started on this sorry.

**Comment by robvdl** [comment]
I have a rudimentary dumpdata command, this includes a new serialize() method on all models.

The serialize method handles many 2 many fields already, and if full=True, it will recursively include these sub models, otherwise a many 2 many field will get serialized into a list of id's instead (the default).

There is also a model.fields property on each model, which the serialize method uses internally, however I think there is going to be a problem with regular (one to many) foreign keys....

That is because SQL Alchemy needs two Python "fields" in the model for representing a foreign key, for example "user_id" (the database column itself) and "user" (the User relationship, this is for Python only)

I have decided I will probably have to make two properties instead for each mode: "model.fields" and "models.columns" maybe, where "fields" will include "person" but not "person_id", and "columns" contains the "actual" database columns so includes "person_id" but not "person".

Foreign keys will most likely be serialized using the Python field "person" and not the column "person_id", and like many 2 many fields, "person" will be an id (int) if full=False, or the serialized Person object if full=True.

**Comment by robvdl** [comment]
The dumpdata command handles both foreign keys and m2m now, just need to finish the loaddata command.

**Comment by robvdl** [comment]
This project is abandoned
